name: Publish Docker image
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: helloworld
    steps:
      - 
        name: Prepare 
        id: prep
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG="latest"
          fi
          echo "::set-output name=tag::${TAG}"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          #platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.tag }} 

